[chains]
[chains.fantom-testnet]
  chain = "fantom-testnet"
  block_time = 1000
  starting_block = 0
  rpcs = ["https://rpc.testnet.fantom.network","https://rpc.ankr.com/fantom_testnet","https://fantom-testnet.public.blastapi.io"]
  threshold_update_block = 10
