version: "3.4"

services:
  mysql:
    container_name: mariadb_container
    image: mariadb:latest
    env_file:
    - .env
    ports:
      - "3306:3306"
    # networks:
    #   - postgres
    restart: unless-stopped
  
  migrate:
    image: migrate/migrate
    volumes:
      - "../database/migrations:/migrations/"
    networks:
      - postgres
    command: [ "-path","/migrations", "-database", "", "up"]

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ACCESS_KEY: access_key
      MINIO_SECRET_KEY: secret_key
    command: server --console-address ":9001" /data

networks:
  postgres:
    driver: bridge

volumes:
    postgres:
