version: "3.4"

services:
  mysql:
    container_name: mariadb
    image: mariadb:latest
    env_file:
    - .env
    ports:
      - 3306:3306
    restart: unless-stopped
    volumes:
      - MYSQL:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 3037:8080

  minio:
    container_name: minio
    image: minio/minio
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ACCESS_KEY: ${STORAGE_ACCESS_KEY}
      MINIO_SECRET_KEY: ${STORAGE_SECRET_KEY}
    command: server --console-address ":9001" /data
    volumes:
      - MINIO:/data

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    container_name: kafka-docker
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka-docker
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper

  redis:
    container_name: redis
    image: redis:6.2-alpine
    restart: always
    ports:
      - 6379:6379

  api-server:
    container_name: api-server
    image: questx:latest
    command: api
    restart: always
    ports:
      - 80:80
      - 8080:8080
    environment:
      API_HOST: 0.0.0.0
      API_PORT: ${API_PORT}
      API_DEFAULT_LIMIT: ${API_DEFAULT_LIMIT}
      API_MAX_LIMIT: ${API_MAX_LIMIT}
      API_ALLOW_CORS: ${API_ALLOW_CORS}
      API_NEED_APPROVE_COMMUNITY: ${API_NEED_APPROVE_COMMUNITY}

      SEARCH_SERVER_ENDPOINT: http://search-server:8082

      MYSQL_DATABASE: questx
      MYSQL_HOST: mysql
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_PORT: 3306
      DATABASE_LOG_LEVEL: ${DATABASE_LOG_LEVEL}

      REDIS_ADDRESS: redis:6379
      KAFKA_ADDRESS: kafka-docker:9092
      STORAGE_ENDPOINT: http://minio:9000
      STORAGE_PUBLIC_ENDPOINT: http://minio:9000
      STORAGE_ACCESS_KEY: ${STORAGE_ACCESS_KEY}
      STORAGE_SECRET_KEY: ${STORAGE_SECRET_KEY}
      STORAGE_SSL_DISABLED: ${STORAGE_SSL_DISABLED}

      TOKEN_SECRET: ${TOKEN_SECRET}
      ACCESS_TOKEN_DURATION: ${ACCESS_TOKEN_DURATION}
      REFRESH_TOKEN_DURATION: ${REFRESH_TOKEN_DURATION}
      AUTH_SESSION_SECRET: ${AUTH_SESSION_SECRET}

      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}

      TWITTER_SCRAPER_ENDPOINT: ${TWITTER_SCRAPER_ENDPOINT}
      TWITTER_CLIENT_ID: ${TWITTER_CLIENT_ID}
      TWITTER_CONSUMER_API_KEY: ${TWITTER_CONSUMER_API_KEY}
      TWITTER_CONSUMER_API_SECRET: ${TWITTER_CONSUMER_API_SECRET}
      TWITTER_ACCESS_TOKEN: ${TWITTER_ACCESS_TOKEN}
      TWITTER_ACCESS_TOKEN_SECRET: ${TWITTER_ACCESS_TOKEN_SECRET}
      TWITTER_APP_ACCESS_TOKEN: ${TWITTER_APP_ACCESS_TOKEN}
      TWITTER_RECLAIM_DELAY: ${TWITTER_RECLAIM_DELAY}

      DISCORD_BOT_TOKEN: ${DISCORD_BOT_TOKEN}
      DISCORD_BOT_ID: ${DISCORD_BOT_ID}

      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      TELEGRAM_LOGIN_EXPIRATION: ${TELEGRAM_LOGIN_EXPIRATION}

      QUIZ_MAX_QUESTIONS: ${QUIZ_MAX_QUESTIONS}
      QUIZ_MAX_OPTIONS: ${QUIZ_MAX_OPTIONS}

      MAX_FILE_SIZE: ${MAX_FILE_SIZE}
      MAX_MEMORY_MULTIPART_FORM: ${MAX_MEMORY_MULTIPART_FORM}
      AVATAR_CROP_HEIGHT: ${AVATAR_CROP_HEIGHT}
      AVATAR_CROP_WIDTH: ${AVATAR_CROP_WIDTH}

      GAME_MIN_LUCKYBOX_EVENT_DURATION: ${GAME_MIN_LUCKYBOX_EVENT_DURATION}
      GAME_MAX_LUCKYBOX_EVENT_DURATION: ${GAME_MAX_LUCKYBOX_EVENT_DURATION}
      GAME_MAX_LUCKYBOX_PER_EVENT: ${GAME_MAX_LUCKYBOX_PER_EVENT}

    depends_on:
      - mysql
      - kafka

  cron:
    container_name: cron
    image: questx:latest
    command: cron
    restart: always
    environment:
      MYSQL_DATABASE: questx
      MYSQL_HOST: mysql
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_PORT: 3306
      DATABASE_LOG_LEVEL: ${DATABASE_LOG_LEVEL}
      KAFKA_ADDRESS: kafka-docker:9092
    depends_on:
      - mysql

  game-proxy:
    container_name: game-proxy
    command: game_proxy
    image: questx:latest
    restart: always
    ports:
      - 8081:8081
    environment:
      MYSQL_DATABASE: questx
      MYSQL_HOST: mysql
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_PORT: 3306
      DATABASE_LOG_LEVEL: ${DATABASE_LOG_LEVEL}

      GAMRE_PROXY_HOST: 0.0.0.0
      GAMRE_PROXY_PORT: 8081
      GAME_PROXY_ALLOW_CORS: ${GAME_PROXY_ALLOW_CORS}
      GAME_MAX_USERS: ${GAME_MAX_USERS}
      GAME_BATCHING_FREQUENCY: ${GAME_BATCHING_FREQUENCY}

      TOKEN_SECRET: ${TOKEN_SECRET}

      KAFKA_ADDRESS: kafka-docker:9092
      REDIS_ADDRESS: redis:6379
    depends_on:
      - mysql
      - kafka

  search-server:
    container_name: search-server
    image: questx:latest
    command: search
    restart: always
    ports:
      - 8082:8082
    environment:
      SEARCH_SERVER_HOST: 0.0.0.0
      SEARCH_SERVER_PORT: 8082
      SEARCH_SERVER_INDEX_DIR: ${SEARCH_SERVER_INDEX_DIR}
      SEARCH_SERVER_RPC_NAME: ${SEARCH_SERVER_RPC_NAME}

  game-center:
    container_name: game-center
    image: questx:latest
    command: game_center
    restart: always
    environment:
      MYSQL_DATABASE: questx
      MYSQL_HOST: mysql
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_PORT: 3306
      DATABASE_LOG_LEVEL: ${DATABASE_LOG_LEVEL}

      KAFKA_ADDRESS: kafka-docker:9092

      GAME_CENTER_JANITOR_FREQUENCY: ${GAME_CENTER_JANITOR_FREQUENCY}
      GAME_CENTER_LOAD_BALANCE_FREQUENCY: ${GAME_CENTER_LOAD_BALANCE_FREQUENCY}
      GAME_ENGINE_PING_FREQUENCY: ${GAME_ENGINE_PING_FREQUENCY}
    depends_on:
      - mysql
      - kafka

  game-engine:
    container_name: game-engine
    image: questx:latest
    command: game_engine
    restart: always
    environment:
      MYSQL_DATABASE: questx
      MYSQL_HOST: mysql
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_PORT: 3306
      DATABASE_LOG_LEVEL: ${DATABASE_LOG_LEVEL}
      
      KAFKA_ADDRESS: kafka-docker:9092
      REDIS_ADDRESS: redis:6379

      STORAGE_ENDPOINT: http://minio:9000
      STORAGE_PUBLIC_ENDPOINT: http://minio:9000

      GAME_SAVE_FREQUENCY: ${GAME_SAVE_FREQUENCY}
      GAME_MOVING_ACTION_DELAY: ${GAME_MOVING_ACTION_DELAY}
      GAME_INIT_ACTION_DELAY: ${GAME_INIT_ACTION_DELAY}
      GAME_JOIN_ACTION_DELAY: ${GAME_JOIN_ACTION_DELAY}
      GAME_MESSAGE_ACTION_DELAY: ${GAME_MESSAGE_ACTION_DELAY}
      GAME_COLLECT_LUCKYBOX_ACTION_DELAY: ${GAME_COLLECT_LUCKYBOX_ACTION_DELAY}
      GAME_MESSAGE_HISTORY_LENGTH: ${GAME_MESSAGE_HISTORY_LENGTH}
      GAME_LUCKYBOX_GENERATE_MAX_RETRY: ${GAME_LUCKYBOX_GENERATE_MAX_RETRY}
    depends_on:
      - mysql
      - kafka

volumes:
    MYSQL:
      name: MYSQL
    MINIO:
      name: MINIO
