version: "3.4"

services:
  mysql:
    container_name: mariadb
    image: mariadb:latest
    env_file:
    - .env
    ports:
      - 3306:3306
    restart: unless-stopped
    volumes:
      - MYSQL:/var/lib/mysql

  scylladb:
    image: "scylladb/scylla"
    container_name: scylladb
    restart: always
    ports:
      - 9042:9042
    volumes:
      - SCYLLA_DB:/var/lib/scylla

  adminer:
    image: adminer
    restart: always
    ports:
      - 3037:8080

  minio:
    container_name: minio
    image: minio/minio
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ACCESS_KEY: ${STORAGE_ACCESS_KEY}
      MINIO_SECRET_KEY: ${STORAGE_SECRET_KEY}
    command: server --console-address ":9001" /data
    volumes:
      - MINIO:/data

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    container_name: kafka-docker
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka-docker
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper

  redis:
    container_name: redis
    image: redis:6.2-alpine
    restart: always
    ports:
      - 6379:6379

  api-server:
    container_name: api-server
    image: questx:latest
    command: api
    restart: always
    ports:
      - 80:80
      - 8080:8080
    environment:
      API_HOST: 0.0.0.0
      API_PORT: ${API_PORT}
      API_DEFAULT_LIMIT: ${API_DEFAULT_LIMIT}
      API_MAX_LIMIT: ${API_MAX_LIMIT}
      API_ALLOW_CORS: ${API_ALLOW_CORS}
      API_NEED_APPROVE_COMMUNITY: ${API_NEED_APPROVE_COMMUNITY}

      SCYLLA_DB_ADDRESS: scylladb:9042
      SCYLLA_DB_KEY_SPACE: xquest

      SEARCH_SERVER_ENDPOINT: http://search-server:8082
      BLOCKCHAIN_ENDPOINT: http://blockchain:8086
      NOTIFICATION_ENGINE_RPC_ENDPOINT: http://notification-engine:8087

      MYSQL_DATABASE: questx
      MYSQL_HOST: mysql
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_PORT: 3306
      DATABASE_LOG_LEVEL: ${DATABASE_LOG_LEVEL}

      REDIS_ADDRESS: redis:6379
      KAFKA_ADDRESS: kafka-docker:9092
      STORAGE_ENDPOINT: http://minio:9000
      STORAGE_PUBLIC_ENDPOINT: http://minio:9000
      STORAGE_ACCESS_KEY: ${STORAGE_ACCESS_KEY}
      STORAGE_SECRET_KEY: ${STORAGE_SECRET_KEY}
      STORAGE_SSL_DISABLED: ${STORAGE_SSL_DISABLED}

      TOKEN_SECRET: ${TOKEN_SECRET}
      ACCESS_TOKEN_DURATION: ${ACCESS_TOKEN_DURATION}
      REFRESH_TOKEN_DURATION: ${REFRESH_TOKEN_DURATION}
      AUTH_SESSION_SECRET: ${AUTH_SESSION_SECRET}

      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}

      TWITTER_SCRAPER_ENDPOINTS: ${TWITTER_SCRAPER_ENDPOINTS}
      TWITTER_CLIENT_ID: ${TWITTER_CLIENT_ID}
      TWITTER_CONSUMER_API_KEY: ${TWITTER_CONSUMER_API_KEY}
      TWITTER_CONSUMER_API_SECRET: ${TWITTER_CONSUMER_API_SECRET}
      TWITTER_ACCESS_TOKEN: ${TWITTER_ACCESS_TOKEN}
      TWITTER_ACCESS_TOKEN_SECRET: ${TWITTER_ACCESS_TOKEN_SECRET}
      TWITTER_APP_ACCESS_TOKEN: ${TWITTER_APP_ACCESS_TOKEN}
      TWITTER_RECLAIM_DELAY: ${TWITTER_RECLAIM_DELAY}

      DISCORD_BOT_TOKEN: ${DISCORD_BOT_TOKEN}
      DISCORD_BOT_ID: ${DISCORD_BOT_ID}

      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      TELEGRAM_LOGIN_EXPIRATION: ${TELEGRAM_LOGIN_EXPIRATION}

      QUIZ_MAX_QUESTIONS: ${QUIZ_MAX_QUESTIONS}
      QUIZ_MAX_OPTIONS: ${QUIZ_MAX_OPTIONS}

      MAX_FILE_SIZE: ${MAX_FILE_SIZE}
      MAX_MEMORY_MULTIPART_FORM: ${MAX_MEMORY_MULTIPART_FORM}
      AVATAR_CROP_HEIGHT: ${AVATAR_CROP_HEIGHT}
      AVATAR_CROP_WIDTH: ${AVATAR_CROP_WIDTH}

      GAME_MIN_LUCKYBOX_EVENT_DURATION: ${GAME_MIN_LUCKYBOX_EVENT_DURATION}
      GAME_MAX_LUCKYBOX_EVENT_DURATION: ${GAME_MAX_LUCKYBOX_EVENT_DURATION}
      GAME_MAX_LUCKYBOX_PER_EVENT: ${GAME_MAX_LUCKYBOX_PER_EVENT}

      INVITE_COMMUNITY_REQUIRED_FOLLOWERS: ${INVITE_COMMUNITY_REQUIRED_FOLLOWERS}
      INVITE_COMMUNITY_REWARD_CHAIN: ${INVITE_COMMUNITY_REWARD_CHAIN}
      INVITE_COMMUNITY_REWARD_TOKEN_ADDRESS: ${INVITE_COMMUNITY_REWARD_TOKEN_ADDRESS}
      INVITE_COMMUNITY_REWARD_AMOUNT: ${INVITE_COMMUNITY_REWARD_AMOUNT}

      BLOCKCHAIN_SECRET_KEY: ${BLOCKCHAIN_SECRET_KEY}
      CACHE_TTL: ${CACHE_TTL}

      CHAT_MESSAGE_XP: ${CHAT_MESSAGE_XP}
      CHAT_IMAGE_MESSAGE_XP: ${CHAT_IMAGE_MESSAGE_XP}
      CHAT_VIDEO_MESSAGE_XP: ${CHAT_VIDEO_MESSAGE_XP}
      CHAT_REACTION_XP: ${CHAT_REACTION_XP}

    depends_on:
      - mysql
      - kafka
      - scylladb

  cron:
    container_name: cron
    image: questx:latest
    command: cron
    restart: always
    environment:
      MYSQL_DATABASE: questx
      MYSQL_HOST: mysql
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_PORT: 3306
      DATABASE_LOG_LEVEL: ${DATABASE_LOG_LEVEL}
      KAFKA_ADDRESS: kafka-docker:9092
    depends_on:
      - mysql


  blockchain:
    container_name: blockchain
    image: questx:latest
    command: blockchain
    restart: always
    ports:
      - 8086:8086
    environment:
      BLOCKCHAIN_HOST: 0.0.0.0
      BLOCKCHAIN_PORT: 8086

      MYSQL_DATABASE: questx
      MYSQL_HOST: mysql
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_PORT: 3306
      DATABASE_LOG_LEVEL: ${DATABASE_LOG_LEVEL}

      REDIS_ADDRESS: redis:6379

      STORAGE_ENDPOINT: http://minio:9000
      STORAGE_PUBLIC_ENDPOINT: http://minio:9000

      BLOCKCHAIN_SECRET_KEY: ${BLOCKCHAIN_SECRET_KEY}
      BLOCKCHAIN_REFRESH_CONENCTION_FREQUENCY: ${BLOCKCHAIN_REFRESH_CONENCTION_FREQUENCY}

    depends_on:
      - mysql
      - kafka

  notification-proxy:
    container_name: notification-proxy
    image: questx:latest
    command: notification_proxy
    restart: always
    ports:
      - 8089:8089
    environment:
      NOTIFICATION_PROXY_HOST: 0.0.0.0
      NOTIFICATION_PROXY_PORT: 8089
      NOTIFICATION_PROXY_ALLOW_CORS: ${NOTIFICATION_PROXY_ALLOW_CORS}

      NOTIFICATION_ENGINE_WS_ENDPOINT: ws://notification-engine:8088/proxy

      MYSQL_DATABASE: questx
      MYSQL_HOST: mysql
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_PORT: 3306
      DATABASE_LOG_LEVEL: ${DATABASE_LOG_LEVEL}

      TOKEN_SECRET: ${TOKEN_SECRET}

      SCYLLA_DB_ADDRESS: scylladb:9042
      SCYLLA_DB_KEY_SPACE: xquest

      CACHE_TTL: ${CACHE_TTL}

    depends_on:
      - mysql
      - kafka
      - scylladb

  notification-engine:
    container_name: notification-engine
    image: questx:latest
    command: notification_engine
    restart: always
    ports:
      - 8087:8087
      - 8088:8088
    environment:
      NOTIFICATION_ENGINE_RPC_HOST: 0.0.0.0
      NOTIFICATION_ENGINE_RPC_PORT: 8087
      NOTIFICATION_ENGINE_WS_HOST: 0.0.0.0
      NOTIFICATION_ENGINE_WS_PORT: 8088

volumes:
    MYSQL:
      name: MYSQL
    MINIO:
      name: MINIO
    SCYLLA_DB:
      name: SCYLLA_DB
