version: "3.4"

services:
  mysql:
    container_name: mariadb_container
    image: mariadb:latest
    env_file:
    - .env
    ports:
      - "3306:3306"
    # networks:
    #   - postgres
    restart: unless-stopped
    volumes:
      - MYSQL:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 3037:8080

  migrate:
    image: migrate/migrate
    volumes:
      - "../database/migrations:/migrations/"
    networks:
      - postgres
    command: [ "-path","/migrations", "-database", "", "up"]

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ACCESS_KEY: access_key
      MINIO_SECRET_KEY: secret_key
    command: server --console-address ":9001" /data
    volumes:
      - MINIO:/data

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper

  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'

networks:
  postgres:
    driver: bridge

volumes:
    postgres:
    MYSQL:
      name: MYSQL
    MINIO:
      name: MINIO
