apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "eureka.fullname" . }}
  labels:
    {{- include "eureka.labels" . | nindent 4 }}
data:
  config.yaml: |
{{ tpl ("configs/config.yaml" | .Files.Get) . | indent 4 }}
 
