apiVersion: v1
kind: Secret
metadata:
  name: { { include "eureka.fullname" . } }
type: Opaque
data:
  OAUTH2_GOOGLE_CLIENT_SECRET: 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
  MYSQL_PASSWORD: e21c60eba1717bbffc0a1b697f8cdea647122e5e62fe9e641035d0c521db5431
  TOKEN_SECRET: random
  AUTH_SESSION_SECRET: random
