apiVersion: v1
kind: Secret
metadata:
  name: {{ include "eureka.fullname" . }}
type: Opaque
data:
{{- if eq "local" .Values.global.environment }}
  service_credential.json: |-
{{ .Values.global.secrets.serviceCredential | indent 4 }}
{{- end }}

  eureka.secrets.yaml.encrypted: |-
{{ printf "secrets/%s/%s/eureka.secrets.yaml.encrypted.base64" .Values.global.vendor .Values.global.environment  | .Files.Get  | indent 4 }}
  eureka_migrate.secrets.yaml.encrypted: |-
{{ printf "secrets/%s/%s/eureka_migrate.secrets.yaml.encrypted.base64" .Values.global.vendor .Values.global.environment  | .Files.Get  | indent 4 }}

{{- if .Values.yugabyteDeployment.enabled }}
  eureka_yugabyte.secrets.yaml.encrypted: |-
{{ printf "secrets/%s/%s/eureka_yugabyte.secrets.yaml.encrypted.base64" .Values.global.vendor .Values.global.environment  | .Files.Get  | indent 4 }}
  eureka_migration.secrets.yaml.encrypted: |
{{ printf "secrets/%s/%s/eureka_migration.secrets.yaml.encrypted.base64" .Values.global.vendor .Values.global.environment  | .Files.Get  | indent 4 }}
{{- end }}

  hasura.secrets.yaml.encrypted: |-
{{ printf "secrets/%s/%s/hasura.secrets.yaml.encrypted.base64" .Values.global.vendor .Values.global.environment | .Files.Get | indent 4 }}
