apiVersion: v1
data:
  AUTH_SESSION_SECRET: dTU/a1kk
  MYSQL_PASSWORD: ZTIxYzYwZWJhMTcxN2JiZmZjMGExYjY5N2Y4Y2RlYTY0NzEyMmU1ZTYyZmU5ZTY0MTAzNWQwYzUyMWRiNTQzMQ==
  OAUTH2_GOOGLE_CLIENT_SECRET: R09DU1BYLVBUOW9WOThENUFnMXlGUDBYUUtiODM4Q20tdmI=
  TOKEN_SECRET: JmYyVyZtQzczQXVYS054eE5e
kind: Secret
metadata:
  creationTimestamp: "2023-03-30T14:20:53Z"
  name: postgres-config
  namespace: backend
  resourceVersion: "668"
  uid: 986c069f-0c23-4903-bb93-bf68d7b15ca3
type: Opaque