apiVersion: v1
data:
  AUTH_SESSION_SECRET: dTU/a1kk
  MYSQL_PASSWORD: ZTIxYzYwZWJhMTcxN2JiZmZjMGExYjY5N2Y4Y2RlYTY0NzEyMmU1ZTYyZmU5ZTY0MTAzNWQwYzUyMWRiNTQzMQ==
  OAUTH2_GOOGLE_CLIENT_SECRET: R09DU1BYLVBUOW9WOThENUFnMXlGUDBYUUtiODM4Q20tdmI=
  TOKEN_SECRET: JmYyVyZtQzczQXVYS054eE5e
kind: Secret
metadata:
  creationTimestamp: "2023-03-29T15:08:48Z"
  name: config
  namespace: default
  resourceVersion: "1254"
  uid: d5102209-88d7-4efb-a84f-e0873b3b2ea9
type: Opaque