apiVersion: v1
kind: Secret
metadata:
  name: { { include "backend.fullname" . } }
type: Opaque
data:
  OAUTH2_GOOGLE_CLIENT_SECRET: draft
  MYSQL_PASSWORD: draft
  TOKEN_SECRET: random
  AUTH_SESSION_SECRET: random
