version: "3.4"

services:
  mysql:
    container_name: mariadb_container
    image: mariadb:latest
    env_file:
    - .env
    ports:
      - "3306:3306"
    # networks:
    #   - postgres
    restart: unless-stopped
  
  migrate:
    image: migrate/migrate
    volumes:
      - "../database/migrations:/migrations/"
    networks:
      - postgres
    command: [ "-path","/migrations", "-database", "", "up"]

networks:
  postgres:
    driver: bridge

volumes:
    postgres:
