apiVersion: v1
data:
  AUTH_SESSION_SECRET: dTU/a1kk
  MYSQL_PASSWORD: ZTIxYzYwZWJhMTcxN2JiZmZjMGExYjY5N2Y4Y2RlYTY0NzEyMmU1ZTYyZmU5ZTY0MTAzNWQwYzUyMWRiNTQzMQ==
  OAUTH2_GOOGLE_CLIENT_SECRET: R09DU1BYLVBUOW9WOThENUFnMXlGUDBYUUtiODM4Q20tdmI=
  TOKEN_SECRET: JmYyVyZtQzczQXVYS054eE5e
kind: Secret
metadata:
  name: gameproxy
  namespace: backend
type: Opaque
