apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: search-pv-claim
spec:
  spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard-rwo
  volumeMode: Filesystem
  volumeName: search-pv-claim