apiVersion: v1
kind: Service
metadata:
  name: {{ include "gameengine.fullname" . }}
  labels:
    {{- include "gameengine.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: 8084
      targetPort: http
      protocol: TCP
      name: http-1
    - port: 8085
      targetPort: http
      protocol: TCP
      name: http-2
  selector:
    {{- include "gameengine.selectorLabels" . | nindent 4 }}
